# Site
name: 'The Campus Chronicle'
description: "Union County Vocational-Technical Schools' Student Newspaper."
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'the-campus-chronicle'
email: 'akashdub06@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
  evie:
      name:           Evie Shen
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Evie Shen is a senior at Magnet High School and Content Editor-in-Chief of Newspaper Club. She joined Newspaper Club due to her love for reading and writing and hopes to increase the impact and voices of the club members’ pieces. In her free time, she enjoys reading, dancing, and playing with her two kittens."
      email:          eshen2@ucvts.org
      school:         Magnet
      grade:          Senior

  lillian:
      name:           Lillian Yu
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Lillian Yu is a junior at Magnet High School. She loves reading and enjoys learning new things. In her free time, she bakes and takes care of her houseplants, her favorite being the monstera. In the future, Lillian wants to go into engineering, with an interest in civil engineering specifically."
      email:          lyu@ucvts.org
      school:         Magnet
      grade:          Junior

  paige:
      name:           Paige Porciello
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Paige is proud to serve as your Layout EIC this year!  She does color guard, volunteers at an observatory, codes often (also serving as co-President of Coding Club), pet-sits for her neighbors, and is skilled in visual arts.  One fun fact about her is that her last name is derived from an insult.  She hopes to pursue a career in astrophysics and frequently writes about astronomy news and concepts for the Campus Chronicle."
      email:          pporciello@ucvts.org
      school:         AIT
      grade:          Senior

  amelia:
      name:           Amelia Hajduk
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Amelia Hajduk is a senior at the Academy for Performing Arts and serves as the Co-Editor-in-Chief of the Literary Magazine, Student Voices. She has a great passion for journalism, and is grateful for the opportunity to oversee this creative process. Outside of Newspaper Club, she loves reading, writing, traveling, and stage managing productions."
      email:          ahajduk@ucvts.org
      school:         APA
      grade:          Senior

  adrija:
      name:           Adrija Adhikary
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Adrija Adhikary is a junior at Magnet High School who serves as the Editor-in-Chief of Student Voices, the campus literary magazine. Outside of curating student poetry and prose, she is deeply passionate about her own creative writing, dabbling in poems and short stories on various topics. An avid reader with a perpetually overflowing 'to-read' pile, Adrija spends her free time hunting for writing prompts on Pinterest and searching the local library catalog for interesting book titles. She is thrilled to publish Student Voices this year and can’t wait to showcase the incredible talent and diverse voices of the UCVTS community."
      email:          aadhikary@ucvts.org
      school:         Magnet
      grade:          Junior

  sharika:
      name:           Sharika Dhar
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Sharika Dhar is a senior at Allied Health and is so excited to serve as Public Relations Editor-in-Chief! Sharika joined Newspaper in her freshman year to grow her passion for journalism. She enjoys working with other writers and helping them find their voice. In her free team, she loves biking, working out, playing with her dog, and listening to music!"
      email:          sdhar@ucvts.org
      school:         AAHS
      grade:          Senior

  saidey:
      name:           Saidey Kim
      avatar:         /assets/images/avatars/anonymous.jpg
      role:           Editor-in-Chief
      bio:            "Saidey Kim is a junior at the Academy for Allied Health Sciences and serves as one of the Public Relations Editors-in-Chief. She is passionate about writing, journalism, and staying informed about current events. In her free time, Saidey enjoys reading, writing, following the news, and playing tennis. She looks forward to contributing to the Campus Chronicle and helping share stories that keep the UCVTS community informed."
      email:          skim1@ucvts.org
      school:         AAHS
      grade:          Junior
        
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: [ akash ]
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
